services:
  web:
    build: ./core

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./core/:/app/back/
    
    ports:
      - 8000:8000
    
    env_file:
      - ./.env.example