services:
  web:
    build: ./core

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./core/:/app/back/
    
    ports:
      - 8000:8000
    
    env_file:
      - ./.env.example
    
    depends_on:
      - db
  
  db:
    image: postgres:16.3-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    env_file:
      - ./.env.example

volumes:
  postgres_data: