# Generated by Django 5.1.1 on 2024-09-29 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id_offer", models.SmallAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=10)),
                (
                    "number_seats",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("discount", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
