# Generated by Django 5.1.1 on 2024-09-29 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"verbose_name": "Offre", "verbose_name_plural": "Offres"},
        ),
        migrations.AlterField(
            model_name="offer",
            name="discount",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Réduction (%)"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="number_seats",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Nombre de place",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="type",
            field=models.CharField(max_length=10, verbose_name="Type d'offre"),
        ),
    ]
