# Generated by Django 5.1.1 on 2024-09-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0002_alter_offer_options_alter_offer_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="type",
            field=models.CharField(max_length=50, verbose_name="Type d'offre"),
        ),
    ]
