# Generated by Django 5.1.1 on 2024-09-29 19:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id_event", models.SmallAutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=50)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                ("id_sport", models.SmallAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="images/sports")),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id_competition",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Femme", "Femme"),
                            ("Homme", "Homme"),
                            ("Mixte", "Mixte"),
                        ],
                        max_length=5,
                    ),
                ),
                ("phase", models.CharField(max_length=50)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="event.sport"
            ),
        ),
    ]
