# Generated by Django 5.1.1 on 2024-09-29 21:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={
                "verbose_name": "Compétition",
                "verbose_name_plural": "Compétitions",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Évènement", "verbose_name_plural": "Évènements"},
        ),
        migrations.AlterModelOptions(
            name="sport",
            options={
                "verbose_name": "Épreuve sportive",
                "verbose_name_plural": "Épreuves sportives",
            },
        ),
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=models.CharField(max_length=50, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.event",
                verbose_name="Évènement",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="gender",
            field=models.CharField(
                choices=[("Femme", "Femme"), ("Homme", "Homme"), ("Mixte", "Mixte")],
                max_length=5,
                verbose_name="Genre",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="phase",
            field=models.CharField(max_length=50, verbose_name="Phase"),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=50, verbose_name="Lieu"),
        ),
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Prix (€)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.sport",
                verbose_name="Épreuves sportives",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="sport",
            name="image",
            field=models.ImageField(upload_to="images/sports", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="sport",
            name="title",
            field=models.CharField(max_length=30, verbose_name="Sport"),
        ),
    ]
