# Generated by Django 5.1.1 on 2024-09-29 19:49

import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0001_initial"),
        ("promotion", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id_booking",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking_Line",
            fields=[
                (
                    "id_booking_line",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("buy_token", models.CharField(max_length=250, unique=True)),
                (
                    "qrcode",
                    private_storage.fields.PrivateFileField(
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="qrcode",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.booking",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotion.offer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking_Line_Person",
            fields=[
                (
                    "id_booking_line_person",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                (
                    "booking_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.booking_line",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.person"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking_line", "person"),
                        name="unique_booking_line_person",
                    )
                ],
            },
        ),
    ]
