# Generated by Django 5.1.1 on 2024-09-29 21:43

import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_competition_options_alter_event_options_and_more"),
        ("promotion", "0002_alter_offer_options_alter_offer_discount_and_more"),
        ("reservation", "0001_initial"),
        ("user", "0002_alter_customer_options_alter_person_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
            },
        ),
        migrations.AlterModelOptions(
            name="booking_line",
            options={
                "verbose_name": "Ligne de réservation",
                "verbose_name_plural": "Lignes de réservation",
            },
        ),
        migrations.AlterModelOptions(
            name="booking_line_person",
            options={
                "verbose_name": "Spectateur lié à la ligne de réservation",
                "verbose_name_plural": "Spectateurs liés aux lignes de réservation",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de réservation"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.person",
                verbose_name="Nom du client",
            ),
        ),
        migrations.AlterField(
            model_name="booking_line",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.booking",
                verbose_name="Réservation",
            ),
        ),
        migrations.AlterField(
            model_name="booking_line",
            name="buy_token",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Clé d'achat"
            ),
        ),
        migrations.AlterField(
            model_name="booking_line",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.event",
                verbose_name="Évènement",
            ),
        ),
        migrations.AlterField(
            model_name="booking_line",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="promotion.offer",
                verbose_name="Type d'offre",
            ),
        ),
        migrations.AlterField(
            model_name="booking_line",
            name="qrcode",
            field=private_storage.fields.PrivateFileField(
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="qrcode",
                verbose_name="QR Code",
            ),
        ),
        migrations.AlterField(
            model_name="booking_line_person",
            name="booking_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.booking_line",
                verbose_name="Ligne de réservation",
            ),
        ),
        migrations.AlterField(
            model_name="booking_line_person",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.person",
                verbose_name="Nom du spectateur",
            ),
        ),
    ]
