# Generated by Django 5.1.1 on 2024-09-29 21:43

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "verbose_name": "Spectateur",
                "verbose_name_plural": "Spectateurs",
            },
        ),
        migrations.AlterField(
            model_name="customer",
            name="account_token",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Clé de compte"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=100, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=50, verbose_name="Mot de passe"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Numéro de téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="country",
            field=models.CharField(max_length=75, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(verbose_name="Date de naissance"),
        ),
        migrations.AlterField(
            model_name="person",
            name="firstname",
            field=models.CharField(max_length=50, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="person",
            name="lastname",
            field=models.CharField(max_length=50, verbose_name="Nom de famille"),
        ),
    ]
